import React,{useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import * as d3 from 'd3';
import './styles/app.css';

const API='';
function App(){
 const [graph,setGraph]=useState({nodes:[],edges:[],colors:{}}); const [health,setHealth]=useState(null); const [files,setFiles]=useState([]); const [selected,setSelected]=useState(null); const [mode,setMode]=useState('explorer'); const [q,setQ]=useState(''); const [type,setType]=useState('');
 const load=async()=>{const [g,h,f]=await Promise.all([fetch(`${API}/api/graph?type=${encodeURIComponent(type)}&q=${encodeURIComponent(q)}`).then(r=>r.json()),fetch('/api/health').then(r=>r.json()),fetch(`/api/files?type=${encodeURIComponent(type)}&q=${encodeURIComponent(q)}`).then(r=>r.json())]);setGraph(g);setHealth(h);setFiles(f)};
 useEffect(()=>{load()},[q,type]); useEffect(()=>{const t=setInterval(load,10000);return()=>clearInterval(t)},[]);
 const openFile=async p=>setSelected(await fetch(`/api/file?path=${encodeURIComponent(p)}`).then(r=>r.json()));
 return <div className="app">
  <header className="top"><div className="brand"><span className="brand-dot"/>BRAiN</div><nav>{['dashboard','explorer','memory','meetings','health'].map(x=><button className={mode===x?'active':''} onClick={()=>setMode(x)} key={x}>{label(x)}</button>)}</nav><button className="reindex" onClick={async()=>{await fetch('/api/reindex',{method:'POST'});load()}}>↻ REINDEXAR</button></header>
  <div className="sub"><span>OBSIDIAN VAULT</span><span>• {health?.counts.files||0} NOTAS</span><span>• {health?.counts.edges||0} RELAÇÕES</span><span>• ATUALIZAÇÃO AUTOMÁTICA</span></div>
  {mode==='dashboard'&&<Dashboard health={health} graph={graph}/>} 
  {mode==='health'&&<Health health={health}/>} 
  {mode==='explorer'&&<Explorer graph={graph} files={files} q={q} setQ={setQ} type={type} setType={setType} openFile={openFile}/>} 
  {mode==='memory'&&<Explorer graph={graph} files={files} q={q} setQ={setQ} type={type} setType={setType} openFile={openFile} memoryOnly/>}
  {mode==='meetings'&&<Explorer graph={graph} files={files.filter(f=>f.type==='reuniao')} q={q} setQ={setQ} type="reuniao" setType={()=>{}} openFile={openFile}/>} 
  {selected&&<FileModal file={selected} close={()=>setSelected(null)}/>} 
 </div>
}
function label(x){return ({dashboard:'VISÃO',explorer:'EXPLORAR',memory:'MEMÓRIA',meetings:'REUNIÕES',health:'SAÚDE'})[x]||x}
function Dashboard({health,graph}){return <main className="dashboard"><section className="hero"><div className="eyebrow">SAÚDE DO CÉREBRO</div><div className="score">{health?.score??'—'}</div><div className="score-label">DE 100</div><div className="radar"><Radar health={health}/></div></section><section className="stats">{[['NOTAS',health?.counts.files],['RELAÇÕES',health?.counts.edges],['CONEXÕES',health?.connectivity+'%'],['FRESCOR',health?.freshness+'%']].map(([a,b])=><div className="stat" key={a}><span>{a}</span><strong>{b??'—'}</strong></div>)}</section><section className="graph-card"><div className="section-title">MAPA DE CONHECIMENTO</div><Graph graph={graph}/></section></main>}
function Explorer({graph,files,q,setQ,type,setType,openFile,memoryOnly=false}){const shown=memoryOnly?files.filter(f=>f.type==='memoria'):files;return <main className="explorer"><aside><div className="section-title">EXPLORADOR</div><input placeholder="Buscar nota ou pasta..." value={q} onChange={e=>setQ(e.target.value)}/><div className="filters">{['','cliente','projeto','reuniao','ferramenta','memoria','documento'].map(t=><button className={type===t?'selected':''} onClick={()=>setType(t)} key={t}>{t||'TODOS'}</button>)}</div><div className="file-list">{shown.map(f=><button className="file" key={f.path} onClick={()=>openFile(f.path)}><span className="file-type">{f.type}</span><span>{f.name}</span><small>{f.path}</small></button>)}</div></aside><section className="graph-card explorer-graph"><div className="section-title">GRAFO • {graph.nodes.length} NÓS</div><Graph graph={graph} onSelect={n=>{const f=files.find(x=>x.id===n.id); if(f)openFile(f.path)}}/></section></main>}
function Graph({graph,onSelect}){const ref=useRef(null); useEffect(()=>{const el=ref.current,w=el.clientWidth,h=el.clientHeight||650; const svg=d3.select(el).html('').append('svg').attr('width',w).attr('height',h).attr('viewBox',`0 0 ${w} ${h}`); const g=svg.append('g'); svg.call(d3.zoom().scaleExtent([.2,5]).on('zoom',e=>g.attr('transform',e.transform))); const link=g.append('g').selectAll('line').data(graph.edges).join('line').attr('stroke','#274238').attr('stroke-width',1); const node=g.append('g').selectAll('g').data(graph.nodes).join('g').style('cursor','pointer').on('click',(_,d)=>onSelect?.(d)); node.append('circle').attr('r',d=>Math.min(10,4+d.connections*.8)).attr('fill',d=>graph.colors[d.type]||graph.colors.default||'#56d98c').attr('fill-opacity',.75); node.append('text').text(d=>d.label).attr('x',9).attr('y',3).attr('fill','#aebbb4').attr('font-size','10px'); const sim=d3.forceSimulation(graph.nodes).force('link',d3.forceLink(graph.edges).id(d=>d.id).distance(70)).force('charge',d3.forceManyBody().strength(-120)).force('center',d3.forceCenter(w/2,h/2)).force('collision',d3.forceCollide().radius(d=>8+d.connections)); sim.on('tick',()=>{link.attr('x1',d=>d.source.x).attr('y1',d=>d.source.y).attr('x2',d=>d.target.x).attr('y2',d=>d.target.y);node.attr('transform',d=>`translate(${d.x},${d.y})`)});return()=>sim.stop()},[graph,onSelect]);return <div className="graph" ref={ref}/>}
function Radar({health}){const vals=[health?.freshness||0,health?.connectivity||0,health?.documentation||0,health?.activity||0,health?.validation||0];const pts=vals.map((v,i)=>{const a=-Math.PI/2+i*2*Math.PI/5,r=75*v/100;return `${100+Math.cos(a)*r},${100+Math.sin(a)*r}`}).join(' ');return <svg viewBox="0 0 200 200"><polygon points="100,20 176,75 147,165 53,165 24,75" fill="none" stroke="#244338"/><polygon points="100,50 145,82 128,137 72,137 55,82" fill="none" stroke="#244338"/><polygon points={pts} fill="#56d98c" fillOpacity=".16" stroke="#56d98c"/></svg>}
function Health({health}){const rows=[['FRESCOR',health?.freshness],['CONEXÃO',health?.connectivity],['DOCUMENTAÇÃO',health?.documentation],['ATIVIDADE',health?.activity],['VALIDAÇÃO',health?.validation]];return <main className="health-page"><section className="health-hero"><div className="eyebrow">SAÚDE DO CÉREBRO</div><div className="big-score">{health?.score}<small>/100</small></div><Radar health={health}/></section><section className="health-table">{rows.map(([n,v])=><div className="health-row" key={n}><span>{n}</span><div className="bar"><i style={{width:`${v}%`}}/></div><strong>{v}%</strong></div>)}<div className="pending"><b>PENDENTE DE VALIDAÇÃO</b><span>{health?.pending?.length||0} notas aguardando revisão</span></div></section></main>}
function FileModal({file,close}){return <div className="modal-backdrop" onClick={close}><article className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={close}>×</button><div className="eyebrow">{file.type} · {file.path}</div><h1>{file.name}</h1><div className="meta">{Object.entries(file.frontmatter||{}).map(([k,v])=><span key={k}>{k}: {String(v)}</span>)}</div><div className="markdown" dangerouslySetInnerHTML={{__html:file.html}}/></article></div>}
createRoot(document.getElementById('root')).render(<App/>);
